# Generated by Django 5.0 on 2024-03-11 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="department",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="core.department",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="level",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (100, "100L"),
                    (200, "200L"),
                    (300, "300L"),
                    (400, "400L"),
                    (500, "500L"),
                    (None, "Not a student"),
                ],
                default=None,
                null=True,
            ),
        ),
    ]
