# Generated by Django 5.0 on 2023-12-31 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='semester',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second')], default=1),
        ),
        migrations.AddField(
            model_name='timetable',
            name='session',
            field=models.CharField(default='2023/2024', max_length=15),
        ),
    ]
