# Generated by Django 5.0 on 2024-01-03 06:41

import timetable.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0004_alter_timetable_excluded_week_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timetable",
            name="end_date",
            field=models.DateField(default=timetable.models.now_date),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="excluded_days",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="excluded_week_days",
            field=models.JSONField(
                blank=True, default=timetable.models.default_excluded_week_days
            ),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="start_date",
            field=models.DateField(default=timetable.models.now_date),
        ),
    ]
