# Generated by Django 5.0 on 2024-03-01 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("timetable", "0009_remove_complain_messages_complain_complain_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="complain",
            name="related_course",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.course",
            ),
        ),
        migrations.AlterField(
            model_name="complain",
            name="complain_type",
            field=models.CharField(
                choices=[
                    ("level-conflict", "Level course conflict"),
                    ("other-conflict", "Other confilct"),
                ],
                default="other-conflict",
                max_length=30,
            ),
        ),
    ]
