# Generated by Django 5.0 on 2024-03-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0010_complain_related_course_alter_complain_complain_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complain",
            name="time",
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="complainmessage",
            name="time",
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
