# Generated by Django 5.0 on 2024-03-01 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0011_alter_complain_time_alter_complainmessage_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complainmessage",
            name="reply_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="timetable.complainmessage",
            ),
        ),
    ]
